<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 23" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="C:\Users\Automation\Documents\MatchMe\Automation\MatchMe\tests\TestCase1.py" status="error" test="TestCase1" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "C:\Users\Automation\.p2\pool\plugins\org.python.pydev.core_6.3.2.201803171248\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "C:/Users/Automation/Documents/MatchMe/Automation/MatchMe/tests\TestCase1.py", line 13, in <module>
    class TestCase1(unittest.TestCase, BaseTest):
TypeError: Error when calling the metaclass bases
    Cannot create a consistent method resolution
order (MRO) for bases TestCase, BaseTest
ERROR: Module: TestCase1 could not be imported (file: C:\Users\Automation\Documents\MatchMe\Automation\MatchMe\tests\TestCase1.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="MatchMe TestCase1.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
